project:
  type: website

website:
  title: "Kang Liang"
  navbar:
    background: light
    title: "Kang Liang"
    left:
      # - href: index.qmd
      #   text: Home
      # - news.qmd
      # - project.qmd
      - href: talk.qmd
        text: Talk
      - href: publication.qmd
        text: Publication
      # - award.qmd
      # - contact.qmd
  page-footer:
    border: true
    center: "Copyright 2022-2024, Kang Liang. All rights reserved."
    background: light

format:
  html:
    theme: [cosmo,theme.scss]
    css: styles.css
    toc: true
    fontsize: "16px"
    linestretch: 1.6
    mainfont: "Roboto"
    smooth-scroll: true
    code-link: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true